services:
    db:
        image: postgres:15
        container_name: ac-computers-db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: ac-computers
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        image: node:18-alpine
        working_dir: /app
        container_name: ac-computers
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        command: ["sh", "-c", "npm install && npm run dev"]
        depends_on:
            - db

volumes:
    postgres_data:
